theme: jekyll-theme-minimal
title: AEA Data Editor
description: The AEA Data Editor's mission is to design and oversee the AEA journals' strategy for archiving and curating research data and promoting reproducible research.
logo: assets/thumbnail_website_logo.jpg
show_downloads: false
collections:
        next:
                output: true
plugins:
        - jekyll-relative-links
        - jekyll-redirect-from
relative_links:
        enabled:     true
        collections: false

