name: Bug report
about: Something is wrong on the website
labels: bug
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is. 
  validations:
    required: true
- type: textarea
  attributes:
    label: URL
    description:  Provide link to the website or source code most related to the bug. 
  validation:
    required: true
- type: textarea
  attributes:
    label: Suggested fix
    description: Do you have any suggestions on how to fix the bug? Possibly a pull request! 
  validations:
    required: false
- type: checkboxes
  id: environment
  attributes:
    label: Your environment - OS
    options:
      - MacOS
      - Windows
      - other
  validations:
    required: false
- type: checkboxes
  id: browser
  attributes:
    label: Your environment - Browser
    options:
      - Edge
      - Safari
      - Internet Explorer
      - Firefox
      - Chrome
      - Brave
      - Opera
      - Other
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: markdown
  attributes:
    value: "Thanks for completing our form!"
